### ISSUE TITLE
Feature Request: Use System NuGet.Config to prepopulate feeds and credentials

### ISSUE THREAD

**Issue by markzielinski** [NuGetPackageExplorer/NuGetPackageExplorer#1007]
Hi,

It would be much nicer if the NuGet Package Explorer used the standard system NuGet.Config file to automatically prepopulate the feeds that are available to browse, retrieve and publish packages to and used the credentials from the same file.   Any feeds that are added/removed in NuGet Package Explorer should then also be reflected in the system NuGet configuration file a well.

Thanks,
Mark

**Comment by campersau** [comment]
Merging the existing feeds from the global `%APPDATA%\NuGet\NuGet.Config` file would be quite easy to achieve:
```c#
var settings = NuGet.Configuration.Settings.LoadDefaultSettings(null);
var packageSourceProvider = new NuGet.Configuration.PackageSourceProvider(settings);
var packageSources = packageSourceProvider.LoadPackageSources();
```

Writing them back would look like this:
```c#
var packageSource = new NuGet.Configuration.PackageSource("http://...", "name");
packageSourceProvider.AddPackageSource(packageSource);
```

But what should be done with the existing feeds from the NuGetPackageEexplorer settings? Should they be automatically migrated to `%APPDATA%\NuGet\NuGet.Config`? Or should we use a separate `NuGet.Config` file for them?

This would fix https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/629
And https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/259 since the [`PackageSource`](https://github.com/NuGet/NuGet.Client/blob/13da23269a4204f83db660557f7e5e03ff955fd2/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSource.cs) has more metadata like a name and credentials.

**Comment by clairernovotny** [comment]
I think for existing feeds, we'd write a different file so that it doesn't accidently change the system defaults.
