### ISSUE TITLE
PdbInfo scroll box is centered instead of left

### ISSUE THREAD

**Issue by clairernovotny** [NuGetPackageExplorer/NuGetPackageExplorer#1027]
Looks like the control starts centered instead of left. There's also a brief pause/delay loading the tab and I'm not sure why. The data should already be parsed and available.

Can repro with package attacked to #1024 

![image](https://user-images.githubusercontent.com/1427284/84499459-9f805300-ac80-11ea-9505-a591d0878d92.png)

@campersau any ideas?

**Comment by campersau** [comment]
It looks like `ItemsControl`s have `IsTabStop="True"` by default which means as soon as the tab gets selected, the first element within it with `IsTabStop="True"` will receive focus. And since all of the of the `TextBox`es are declared as `IsTabStop="False"`
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/5d556ab2b07ec235dd82ae49eb65c7aaccc317ab/PackageExplorer/App.xaml#L101
the `ItemsControl` receives the focus and get scrolled into view.
This also happens on the `Embedded PDB Sources` tabs, but it is only the [`Margin="3"` from the `Grid`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/5d556ab2b07ec235dd82ae49eb65c7aaccc317ab/PackageExplorer/Controls/PdbSourcesViewer.xaml#L10).

When setting `IsTabStop="False"` on the `ItemsControl` in the `Embedded PDB Info` tab, then currently the first element with `IsTabStop="True"` would be the first cell in the `DataGrid` which also looks odd.

**Comment by clairernovotny** [comment]
@campersau any chance you could please fix it :)
