### ISSUE TITLE
Incorrect path rendering in case of `\\`

### ISSUE THREAD

**Issue by RussKie** [NuGetPackageExplorer/NuGetPackageExplorer#1327]
**Type** (choose one):

- Bug

**NPE version**: NuGet Package Explorer - Chocolatey - X64 - (5.10.43+ce9a70d0c5)

**Installed from**: Chocolatey.org

In case of a BUG:

- What is the current result?

![image](https://user-images.githubusercontent.com/4403806/127106902-356bc0d2-c60d-4947-bd43-c73d009ee8d5.png)

- What is the expected result?

The path should be normalised before rendering (i.e. `\\` should be treated as `\`), no folders with empty name should be shown.

Repro: here's the sample [Microsoft.Private.Winforms.6.0.0-dev.nupkg.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/6884171/Microsoft.Private.Winforms.6.0.0-dev.nupkg.zip) (remove .zip extension).

**Comment by campersau** [comment]
Can you please upload the package here or provide a public nuget feed and id?

**Comment by RussKie** [comment]
It would make easy, won't it :) Thanks for nudge, updated the issue.

**Comment by campersau** [comment]
Thanks for the file! I am not sure if that is something we should fix because that's the way the file was created and we would just hide a potential error. If you open the file with 7-zip or windows explorer (nupkg are just zips with a different suffix) you can see it there as well.

Windows shows the empty folder:
![image](https://user-images.githubusercontent.com/4009570/127136825-c1ea04ef-a599-42e2-a3e7-43e81be5bc2e.png)

And we navigating into it it will show up a `\` in the address bar:
![image](https://user-images.githubusercontent.com/4009570/127136901-e4c14313-66de-4664-913a-c311d4de7a10.png)

Extracting the file with windows explorer will use an `_` instead of an empty string:
![image](https://user-images.githubusercontent.com/4009570/127137257-ea688c50-1527-4080-b50b-203414e13920.png)

Which is what 7-zip is also showing:
![image](https://user-images.githubusercontent.com/4009570/127137817-594f2aa7-5bd1-49c9-89f0-3af384eb187d.png)

**Comment by clairernovotny** [comment]
@RussKie that feels like a bug in the packaging, I agree that we shouldn't be hiding an extra slash that was put in incorrectly.

**Comment by RussKie** [comment]
Thank you for your help.
