### ISSUE TITLE
Not showing .NET 6 correctly on the dependencies

### ISSUE THREAD

**Issue by timheuer** [NuGetPackageExplorer/NuGetPackageExplorer#1367]
The display for net6 is not consistent with others.

**Type** (choose one):

- Bug

**NPE version**: NuGet Package Explorer - Store - X64 - (5.10.43+ce9a70d0c5)

**OS version**: Windows 10

**Installed from**: Microsoft Store

In case of a BUG:
![image](https://user-images.githubusercontent.com/4821/132780894-3e80c63f-ef49-42c8-ba02-2c886428ee6a.png)

**Comment by campersau** [comment]
NuGet.Client returns a different `ToString` value for >= `net5.0` that's why it is also different there.
https://github.com/NuGet/NuGet.Client/blob/f4ae349ec18d1ac5d5e7d1b0ed753e1300e9e157/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs#L458-L463

But in other places we explicitly show the `DotNetFrameworkName` instead, so maybe we should do the same here as well.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/PackageExplorer/Converters/FrameworkNameConverter.cs#L46
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/e6e83b04058e8a30f7662e0570ca5f02e63edb35/PackageExplorer/Converters/FrameworkAssemblyReferenceDisplayConverter.cs#L29
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/PackageExplorer/Converters/FrameworkAssemblyReferenceConverter.cs#L18

Example with fix:
![image](https://user-images.githubusercontent.com/4009570/132819339-3a76043a-0793-427a-8dab-b64306bc8b51.png)

**Comment by svick** [comment]
Since `.NETCoreApp,Version=v5.0` is correct, but also cofusing, wouldn't it be better to show a "friendly" framework name, like ".NET 5.0"? I guess it depends on the target audience of NPE.
