### ISSUE TITLE
Merge in

### ISSUE THREAD

**Issue by caioproiete** [NuGetPackageExplorer/NuGetPackageExplorer#16]
([originally created](https://github.com/dsplaisted/NuGetPackageExplorer/issues/4) by @304NotModified)

Proposal to merge from other forks:

- [x] Support for pushing to authenticated NuGet feed
- [x] Include default credentials in web requests
- [x] Fallback to Packages() service for all versions

**Comment by 304NotModified** [comment]
@rikoe can you check this?

**Comment by rikoe** [comment]
Will do soon. Thanks for reminding me.

**Comment by 304NotModified** [comment]
OK Cool :)

Like to release it after it.

**Comment by 304NotModified** [comment]
@rikoe any idea when you have time for this? 

Thanks in advance!

**Comment by rikoe** [comment]
Hi - sorry, we've had a baby recently so struggling to find time. Will try to do it by Wednesday.

**Comment by 304NotModified** [comment]
@rikoe any success with finding some time?

**Comment by rikoe** [comment]
Hi @304NotModified I have just started pulling the latest code to try and get this done, and have just seen that you have created some branches of your own for this (based on my implementation, or your own, I haven't checked)

I can't really complain  about this, as I did not respond to your previous message and it has been a while since I last said I would try to find some time.

Would you like to continue on on your own, or should I create a PR for these features based on my earlier work?

**Comment by 304NotModified** [comment]
A PR would be great!

I was indeed working on this, but I have difficulties to test it as I don't have the environment to test it.

**Comment by rikoe** [comment]
Testing is the real problem, as I don't have a similar environment with Windows Authentication as when I set this up any more. I have submitted the PR but it needs to be tested so maybe leave it open. I have to see whether I can set up a VM to do it or maybe test it at work.

Anyway, this is all I could manage for today :smile:

**Comment by 304NotModified** [comment]
Fixed by #49
