### ISSUE TITLE
Central Directory corrupt.

### ISSUE THREAD

**Issue by MoMakkawi** [NuGetPackageExplorer/NuGetPackageExplorer#1666]
**Type**:

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)

**OS version**: (Windows 11)

**Installed from**: Build-in Visual Studio 17.9.6 

In case of a BUG:

- What is the current result? 
There is an error when I want to create Minimal API but Native AOT using Visual Studio 17.9.6 
![Screenshot 2024-06-09 145813](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/assets/94985793/9b7a08db-8742-4945-9a10-8b1f3e5e9d0c)

- What is the expected result?
Must the NPM restore all needed packages to run the project successfully.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
ok to make it simple, I did not do any thing in the default template of Visual Studio but the error did not allow me to run the default Native AOT Minimal ASP.NET Core API.

- Are there any workarounds? yes/no
- Is there a version in which it did work?

- Is there a package on Nuget.org which shows the bug?
I don't know I think maybe connection failed between NPM and VS

**Comment by Zastai** [comment]
You're in the wrong place for this bug report - this is not the repository for the Visual Studio Package Manager, nor that of the NuGet client.

"Central directory corrupt." means that the .nupkg file is not a valid zip archive. Given that the central directory is at the end of the file, it is most commonly caused by a truncated file (e.g. because a download did not complete). So it's not a bug anywhere, it's a problem with your network access to nuget.org.

**Comment by MoMakkawi** [comment]
ohhhh , Sorry, I think you are responsible for Visual Studio Package Manager also.
Thank you @Zastai for your kindness and for answering me.
