### ISSUE TITLE
unable to list or publish the packages using NPE with Nuget Server version 3.0.1.0

### ISSUE THREAD

**Issue by cmreddyv** [NuGetPackageExplorer/NuGetPackageExplorer#275]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.24)

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex / Windows Store

In case of a BUG:

- What is the current result?- unable to list/publish the packages to feed using NPE
- What is the expected result?- should publish/list the packages using NPE
- Are there any work arrounds? yes/no- using Nuget command line i am able to list or publish the packages
- Is there a version in which it did worked? - yes with server v 2.11.2.0
- Is there a package on Nuget.org which shows the bug?

**Comment by 304NotModified** [comment]
please update to the latest version (chocolatey or Windows Store).

There was a change in the nuget protocol

**Comment by cmreddyv** [comment]
Dear @304NotModified ,

I am not able to do anything with the latest version as well 3.25.0.0

I am getting error as: An error occured while processing this request. the remote server returned status code:400

**Comment by 304NotModified** [comment]
Are you sure the url is correct and complete?

It's just a http call for listing, so if localhost returns 400, you will get this result

**Comment by cmreddyv** [comment]
@304NotModified , yes the URL is correct, I hosted the Nuget Server in my local IIS.

FYI, I
![nugeturl](https://user-images.githubusercontent.com/33657970/33921472-f619eaac-dfe9-11e7-9ed9-371fd1d4927f.png)
 am able to get the results with the server version 2.11.1.0 but not with the latest version.

**Comment by 304NotModified** [comment]
Isn't nuget.org build on nuget.server 3?

**Comment by cmreddyv** [comment]
This is a plain Nuget server created using a empty web application, this a private server

**Comment by cmreddyv** [comment]
I am using this for hosting my packages.

**Comment by cmreddyv** [comment]
can someone help me on this?

**Comment by onovotny** [comment]
This looks like a bug with NuGet Server, I would suggest posting on https://github.com/NuGet/Home/issues, though I suspect they'll suggest to use NuGetGallery as the v2 code is pretty old.

**Comment by joelverhagen** [comment]
Hey guys, thanks for reporting this issue. The short answer is that NuGet.Server 3.x does not support projection (e.g. `$select`). This is a bug. As @cmreddyv mentioned...

> localhost/nuget/Packages()?$orderby=DownloadCount%20desc&$filter=IsAbsoluteLatestVersion&$skip=0&$top=15&$select=Id,Version,Authors,DownloadCount,VersionDownloadCount,PackageHash,PackageSize,Published&$inlinecount=allpages

... the error is thrown when hitting this URL. If you remove the `$select` query parameter, things will work. I moved @cmreddyv's issue to the NuGetGallery repository as this is a server-side issue:
https://github.com/NuGet/NuGetGallery/issues/5193

I will leave that issue open to track the investigation and bug fix in NuGet.Server 3.x. I think NuGet.Server should support projection. 

However it should be noted that it is best to only use the parameters that the official NuGet.Client uses since these are most tested and supported:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedQueryBuilder.cs

Thanks again for bringing this to our attention.

**Comment by joelverhagen** [comment]
I've released a 3.0.2 version of NuGet.Server. Let me know if you run into any other issues. 👍
