### ISSUE TITLE
BadImageFormatException with drag/drop

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#391]
I'm getting an exception if I try to drag/drop a file. I'm on RS4 (17133):

![image](https://user-images.githubusercontent.com/1427284/38531274-06a6c214-3c3d-11e8-9c9b-4530175ddd42.png)

@campersau 

Looks like if I use NuGetPackageExplorer as the startup project, it works, but if I use PackageExplorer.Package.Nightly, it fails. 

Seems like the wrong assembly is being deployed for System.Memory.

**Comment by campersau** [comment]
I can also reproduce it. Not sure why exactly this is happening at the moment.

**Comment by 304NotModified** [comment]
not a strong naming issue?

**Comment by campersau** [comment]
I don't think so. I have added `StrongNamer` and every dll was already signed:
```
1>    Assembly file 'C:\Users\xxx\.nuget\packages\system.memory\4.5.0-preview1-26216-02\ref\netstandard2.0\System.Memory.dll' is already signed.  Skipping.
```

**Comment by onovotny** [comment]
The reference assm is going to the output directory. I need to investigate by tracing the binlog files. You can tell by looking at the file size that's there.

**Comment by campersau** [comment]
I found the issue!

If you create a normal `WAP` proj and reference a `WPF` app which has `System.Memory` as a dependency. Then the `System.Memory` dll from the `ref` folder is used instead of the one in the `lib` folder. See [example here](https://github.com/campersau/SystemMemoryWindowsApplicationPackaging)

---

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/76e3b798abeedf40dbed5fb9702a9cf0ed50e55a/PackageExplorer.Package.Nightly/PackageExplorer.Package.Nightly.wapproj#L59-L61

Sadly this workaround does not work corrently because the dlls referenced by the `NuGetPackageExplorer` are overridden by the `WAP` build.

(I think you added this hack to also get the dependencies of the dependencies right?)

Try this:

1. Start the `PackageExplorer.Package.Nightly`
2. Before doing anything copy all files from `NuGetPackageExplorer\PackageExplorer\bin\xxx\net461`
3. Ignore any `File is already in use` messages and continue
4. Create a new package
5. Copy / Drag a DLL into NPE

So we have to fix this hack that it somehow copies the dll after the build from `WAP`.
