### ISSUE TITLE
Missing file in file list: PackgeViewModel.dll

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#498]
With the following package, NPE isn't showing PackageViewModel.dll for some reason. Looking at it in zip viewer shows it.

[NugetPackageExplorer.1.2.3.nupkg.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/2519665/NugetPackageExplorer.1.2.3.nupkg.zip)

**Comment by campersau** [comment]
The problem is that the exclude paths contain a `package` value and it is just checked with `StartsWith`.

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/72bb026d85df668515f3b2bbbbb6a86b7d5f0e7c/Core/Packages/ZipPackage.cs#L23

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/72bb026d85df668515f3b2bbbbb6a86b7d5f0e7c/Core/Packages/ZipPackage.cs#L352-L359

**Comment by onovotny** [comment]
Thanks for the analysis. Do you want to submit a PR or should I?
