### ISSUE TITLE
Indicator for Source Link with Symbols

### ISSUE THREAD

**Issue by clairernovotny** [NuGetPackageExplorer/NuGetPackageExplorer#904]
We should have a checkbox/indicator for a package that displays if a package is properly source linked with symbols available.

This is related to #903, but goes further:

- Looks for any symbols, in the package, embedded, or snupkg
- if external, in snupkg, downloads it in the background
- Opens symbols and looks for Source Link data

If all present, display a marker. In the interim, display an indeterminate state marker.

**Comment by AArnott** [comment]
I was just wanting this today. I see you fixed it, which is great. Is it not on the Microsoft Store yet?

**Comment by clairernovotny** [comment]
It's "In Certification" :(

I hate how long the store can take sometimes.

![image](https://user-images.githubusercontent.com/1427284/77827338-673e8f00-70eb-11ea-80d9-e9ebeac97bb0.png)

**Comment by kahlkevin** [comment]
This doesn't seem to work if I'm viewing a locally built, but unpublished .nupkg with the .snupkg sitting right next to it in the same dir.

I'd like for that to work since it's very useful for validation of all the content before publishing.

**Comment by clairernovotny** [comment]
@kahlkevin Please file a new issue with the feature request. In general I strongly discourage use of `snupkg` as only NuGet.org supports it. Best to put the PDB files into the NuPkg. 

You can see a full sample, including how to put pdb's in the nupkg here: https://github.com/clairernovotny/DeterministicBuilds/blob/master/Directory.Build.props#L10

**Comment by AArnott** [comment]
> In general I strongly discourage use of snupkg as only NuGet.org supports it. Best to put the PDB files into the NuPkg.

I prefer `snupkg` because the symbols get indexed so the debugger can find the symbols even for an arbitrary running application, as opposed to only while developing the application when you happen to have pdb's nearby.

And to your point that only nuget.org supports it, that may have been true once but no longer. [MyGet.org supports snupkg](https://docs.myget.org/docs/reference/symbols).
I guess [Azure DevOps](https://developercommunity.visualstudio.com/idea/657354/add-snupkg-support-to-azure-devops-artifacts.html) doesn't support it yet but it looks highly voted.

**Comment by clairernovotny** [comment]
Fair point on getting symbols for other apps. I would hope that the app would publish the PDB files of dependencies alongside the app. Embedded PPDB solves this too ;)

Seems like NuGet should just index PDB's in NuPkg and be done with it. Symbol Servers don't work in air-gapped/offline scenarios whereas if you have the NuPkg locally you're ok. It's also easier to lose the pdb's since they're much more out-of-sight.
